apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: operations_service:v1
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
